services:
  - type: web
    name: henig-b2b
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /
        destination: /index.html
